project:
  type: website

website:
  title: "Mapping the Transnational Circulation and Control of Small Arms in Latin America"
  navbar:
    left:
      - href: index.qmd
        text: "Project"
      - about.qmd
      - outputs.qmd
      - data.qmd
      - team.qmd
      - partners.qmd

format:
  html:
    theme:
      - cosmo
    bslib: true
    css: theme.css
    toc: false
    anchor-sections: false
    include-in-header:
      - text: |
          <link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96"/>
          <link rel="icon" type="image/svg+xml" href="/favicon/favicon.svg"/>
          <link rel="shortcut icon" href="/favicon/favicon.ico"/>
          <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png"/>
          <link rel="manifest" href="/site.webmanifest"/>

editor: visual