project:
  type: website

website:
  title: "Mapping the Transnational Circulation and Control of Small Arms in Latin America"
  navbar:
    left:
      - href: index.qmd
        text: "Project"
      - about.qmd
      - outputs.qmd
      - data.qmd
      - team.qmd
      - partners.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    bslib: true
    css: theme.css
    toc: false
    anchor-sections: false

editor: visual

